#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gcr
Version  : 3.38.0
Release  : 19
URL      : https://download.gnome.org/sources/gcr/3.38/gcr-3.38.0.tar.xz
Source0  : https://download.gnome.org/sources/gcr/3.38/gcr-3.38.0.tar.xz
Summary  : GObject and GUI library for high level crypto parsing and display
Group    : Development/Tools
License  : LGPL-2.0
Requires: gcr-bin = %{version}-%{release}
Requires: gcr-data = %{version}-%{release}
Requires: gcr-lib = %{version}-%{release}
Requires: gcr-libexec = %{version}-%{release}
Requires: gcr-license = %{version}-%{release}
Requires: gcr-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dbus
BuildRequires : dbus-dev
BuildRequires : dbus-extras
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gnupg
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-x11-3.0)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : vala
BuildRequires : vala-dev

%description
GCR is a library for displaying certificates, and crypto UI, accessing
key stores. It also provides the viewer for crypto files on the GNOME
desktop.

%package bin
Summary: bin components for the gcr package.
Group: Binaries
Requires: gcr-data = %{version}-%{release}
Requires: gcr-libexec = %{version}-%{release}
Requires: gcr-license = %{version}-%{release}

%description bin
bin components for the gcr package.


%package data
Summary: data components for the gcr package.
Group: Data

%description data
data components for the gcr package.


%package dev
Summary: dev components for the gcr package.
Group: Development
Requires: gcr-lib = %{version}-%{release}
Requires: gcr-bin = %{version}-%{release}
Requires: gcr-data = %{version}-%{release}
Provides: gcr-devel = %{version}-%{release}
Requires: gcr = %{version}-%{release}

%description dev
dev components for the gcr package.


%package doc
Summary: doc components for the gcr package.
Group: Documentation

%description doc
doc components for the gcr package.


%package lib
Summary: lib components for the gcr package.
Group: Libraries
Requires: gcr-data = %{version}-%{release}
Requires: gcr-libexec = %{version}-%{release}
Requires: gcr-license = %{version}-%{release}

%description lib
lib components for the gcr package.


%package libexec
Summary: libexec components for the gcr package.
Group: Default
Requires: gcr-license = %{version}-%{release}

%description libexec
libexec components for the gcr package.


%package license
Summary: license components for the gcr package.
Group: Default

%description license
license components for the gcr package.


%package locales
Summary: locales components for the gcr package.
Group: Default

%description locales
locales components for the gcr package.


%prep
%setup -q -n gcr-3.38.0
cd %{_builddir}/gcr-3.38.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601314478
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gcr
cp %{_builddir}/gcr-3.38.0/COPYING %{buildroot}/usr/share/package-licenses/gcr/5fb362ef1680e635fe5fb212b55eef4db9ead48f
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gcr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gcr-viewer

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gck-1.typelib
/usr/lib64/girepository-1.0/Gcr-3.typelib
/usr/lib64/girepository-1.0/GcrUi-3.typelib
/usr/share/GConf/gsettings/org.gnome.crypto.pgp.convert
/usr/share/GConf/gsettings/org.gnome.crypto.pgp_keyservers.convert
/usr/share/applications/gcr-prompter.desktop
/usr/share/applications/gcr-viewer.desktop
/usr/share/dbus-1/services/org.gnome.keyring.PrivatePrompter.service
/usr/share/dbus-1/services/org.gnome.keyring.SystemPrompter.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.crypto.pgp.gschema.xml
/usr/share/icons/hicolor/16x16/apps/gcr-gnupg.png
/usr/share/icons/hicolor/16x16/apps/gcr-key-pair.png
/usr/share/icons/hicolor/16x16/apps/gcr-key.png
/usr/share/icons/hicolor/16x16/apps/gcr-password.png
/usr/share/icons/hicolor/16x16/apps/gcr-smart-card.png
/usr/share/icons/hicolor/22x22/apps/gcr-gnupg.png
/usr/share/icons/hicolor/22x22/apps/gcr-key-pair.png
/usr/share/icons/hicolor/22x22/apps/gcr-key.png
/usr/share/icons/hicolor/22x22/apps/gcr-password.png
/usr/share/icons/hicolor/22x22/apps/gcr-smart-card.png
/usr/share/icons/hicolor/24x24/apps/gcr-gnupg.png
/usr/share/icons/hicolor/24x24/apps/gcr-key-pair.png
/usr/share/icons/hicolor/24x24/apps/gcr-key.png
/usr/share/icons/hicolor/24x24/apps/gcr-password.png
/usr/share/icons/hicolor/24x24/apps/gcr-smart-card.png
/usr/share/icons/hicolor/256x256/apps/gcr-gnupg.png
/usr/share/icons/hicolor/256x256/apps/gcr-password.png
/usr/share/icons/hicolor/256x256/apps/gcr-smart-card.png
/usr/share/icons/hicolor/32x32/apps/gcr-gnupg.png
/usr/share/icons/hicolor/32x32/apps/gcr-key-pair.png
/usr/share/icons/hicolor/32x32/apps/gcr-key.png
/usr/share/icons/hicolor/32x32/apps/gcr-password.png
/usr/share/icons/hicolor/32x32/apps/gcr-smart-card.png
/usr/share/icons/hicolor/48x48/apps/gcr-gnupg.png
/usr/share/icons/hicolor/48x48/apps/gcr-key-pair.png
/usr/share/icons/hicolor/48x48/apps/gcr-key.png
/usr/share/icons/hicolor/48x48/apps/gcr-password.png
/usr/share/icons/hicolor/48x48/apps/gcr-smart-card.png
/usr/share/mime-packages/gcr-crypto-types.xml
/usr/share/vala/vapi/gck-1.deps
/usr/share/vala/vapi/gck-1.vapi
/usr/share/vala/vapi/gcr-3.deps
/usr/share/vala/vapi/gcr-3.vapi
/usr/share/vala/vapi/gcr-ui-3.deps
/usr/share/vala/vapi/gcr-ui-3.vapi
/usr/share/vala/vapi/pkcs11.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gck-1/gck/gck-deprecated.h
/usr/include/gck-1/gck/gck-enum-types.h
/usr/include/gck-1/gck/gck-version.h
/usr/include/gck-1/gck/gck.h
/usr/include/gck-1/gck/pkcs11.h
/usr/include/gck-1/gck/pkcs11n.h
/usr/include/gck-1/gck/pkcs11x.h
/usr/include/gcr-3/gcr/gcr-base.h
/usr/include/gcr-3/gcr/gcr-certificate-chain.h
/usr/include/gcr-3/gcr/gcr-certificate-request.h
/usr/include/gcr-3/gcr/gcr-certificate.h
/usr/include/gcr-3/gcr/gcr-collection.h
/usr/include/gcr-3/gcr/gcr-column.h
/usr/include/gcr-3/gcr/gcr-comparable.h
/usr/include/gcr-3/gcr/gcr-deprecated-base.h
/usr/include/gcr-3/gcr/gcr-enum-types-base.h
/usr/include/gcr-3/gcr/gcr-filter-collection.h
/usr/include/gcr-3/gcr/gcr-fingerprint.h
/usr/include/gcr-3/gcr/gcr-icons.h
/usr/include/gcr-3/gcr/gcr-import-interaction.h
/usr/include/gcr-3/gcr/gcr-importer.h
/usr/include/gcr-3/gcr/gcr-library.h
/usr/include/gcr-3/gcr/gcr-mock-prompter.h
/usr/include/gcr-3/gcr/gcr-parser.h
/usr/include/gcr-3/gcr/gcr-pkcs11-certificate.h
/usr/include/gcr-3/gcr/gcr-prompt.h
/usr/include/gcr-3/gcr/gcr-secret-exchange.h
/usr/include/gcr-3/gcr/gcr-secure-memory.h
/usr/include/gcr-3/gcr/gcr-simple-certificate.h
/usr/include/gcr-3/gcr/gcr-simple-collection.h
/usr/include/gcr-3/gcr/gcr-ssh-askpass.h
/usr/include/gcr-3/gcr/gcr-system-prompt.h
/usr/include/gcr-3/gcr/gcr-system-prompter.h
/usr/include/gcr-3/gcr/gcr-trust.h
/usr/include/gcr-3/gcr/gcr-types.h
/usr/include/gcr-3/gcr/gcr-union-collection.h
/usr/include/gcr-3/gcr/gcr-unlock-options.h
/usr/include/gcr-3/gcr/gcr-version.h
/usr/include/gcr-3/gcr/gcr.h
/usr/include/gcr-3/ui/gcr-certificate-basics-widget.h
/usr/include/gcr-3/ui/gcr-certificate-details-widget.h
/usr/include/gcr-3/ui/gcr-certificate-renderer.h
/usr/include/gcr-3/ui/gcr-certificate-widget.h
/usr/include/gcr-3/ui/gcr-collection-model.h
/usr/include/gcr-3/ui/gcr-combo-selector.h
/usr/include/gcr-3/ui/gcr-deprecated.h
/usr/include/gcr-3/ui/gcr-enum-types.h
/usr/include/gcr-3/ui/gcr-failure-renderer.h
/usr/include/gcr-3/ui/gcr-import-button.h
/usr/include/gcr-3/ui/gcr-key-renderer.h
/usr/include/gcr-3/ui/gcr-key-widget.h
/usr/include/gcr-3/ui/gcr-list-selector.h
/usr/include/gcr-3/ui/gcr-prompt-dialog.h
/usr/include/gcr-3/ui/gcr-renderer.h
/usr/include/gcr-3/ui/gcr-secure-entry-buffer.h
/usr/include/gcr-3/ui/gcr-tree-selector.h
/usr/include/gcr-3/ui/gcr-ui.h
/usr/include/gcr-3/ui/gcr-unlock-options-widget.h
/usr/include/gcr-3/ui/gcr-viewer-widget.h
/usr/include/gcr-3/ui/gcr-viewer.h
/usr/lib64/libgck-1.so
/usr/lib64/libgcr-base-3.so
/usr/lib64/libgcr-ui-3.so
/usr/lib64/pkgconfig/gck-1.pc
/usr/lib64/pkgconfig/gcr-3.pc
/usr/lib64/pkgconfig/gcr-base-3.pc
/usr/lib64/pkgconfig/gcr-ui-3.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gck/GckAttribute.html
/usr/share/gtk-doc/html/gck/GckAttributes.html
/usr/share/gtk-doc/html/gck/GckEnumerator.html
/usr/share/gtk-doc/html/gck/GckModule.html
/usr/share/gtk-doc/html/gck/GckObject.html
/usr/share/gtk-doc/html/gck/GckObjectCache.html
/usr/share/gtk-doc/html/gck/GckSession.html
/usr/share/gtk-doc/html/gck/GckSlot.html
/usr/share/gtk-doc/html/gck/annotation-glossary.html
/usr/share/gtk-doc/html/gck/gck-Errors.html
/usr/share/gtk-doc/html/gck/gck-GckModule-lists.html
/usr/share/gtk-doc/html/gck/gck-Library-Utilities.html
/usr/share/gtk-doc/html/gck/gck-Miscellaneous-Functions.html
/usr/share/gtk-doc/html/gck/gck-PKCS11-URIs.html
/usr/share/gtk-doc/html/gck/gck.devhelp2
/usr/share/gtk-doc/html/gck/home.png
/usr/share/gtk-doc/html/gck/index.html
/usr/share/gtk-doc/html/gck/left-insensitive.png
/usr/share/gtk-doc/html/gck/left.png
/usr/share/gtk-doc/html/gck/pkcs11-links.html
/usr/share/gtk-doc/html/gck/reference.html
/usr/share/gtk-doc/html/gck/right-insensitive.png
/usr/share/gtk-doc/html/gck/right.png
/usr/share/gtk-doc/html/gck/style.css
/usr/share/gtk-doc/html/gck/up-insensitive.png
/usr/share/gtk-doc/html/gck/up.png
/usr/share/gtk-doc/html/gcr/GcrCertificate.html
/usr/share/gtk-doc/html/gcr/GcrCertificateChain.html
/usr/share/gtk-doc/html/gcr/GcrCertificateRequest.html
/usr/share/gtk-doc/html/gcr/GcrCertificateWidget.html
/usr/share/gtk-doc/html/gcr/GcrCollection.html
/usr/share/gtk-doc/html/gcr/GcrCollectionModel.html
/usr/share/gtk-doc/html/gcr/GcrComboSelector.html
/usr/share/gtk-doc/html/gcr/GcrComparable.html
/usr/share/gtk-doc/html/gcr/GcrImportButton.html
/usr/share/gtk-doc/html/gcr/GcrImportInteraction.html
/usr/share/gtk-doc/html/gcr/GcrImporter.html
/usr/share/gtk-doc/html/gcr/GcrKeyWidget.html
/usr/share/gtk-doc/html/gcr/GcrListSelector.html
/usr/share/gtk-doc/html/gcr/GcrParser.html
/usr/share/gtk-doc/html/gcr/GcrPkcs11Certificate.html
/usr/share/gtk-doc/html/gcr/GcrPrompt.html
/usr/share/gtk-doc/html/gcr/GcrPromptDialog.html
/usr/share/gtk-doc/html/gcr/GcrRenderer.html
/usr/share/gtk-doc/html/gcr/GcrSecretExchange.html
/usr/share/gtk-doc/html/gcr/GcrSecureEntryBuffer.html
/usr/share/gtk-doc/html/gcr/GcrSimpleCertificate.html
/usr/share/gtk-doc/html/gcr/GcrSimpleCollection.html
/usr/share/gtk-doc/html/gcr/GcrSshAskpass.html
/usr/share/gtk-doc/html/gcr/GcrSystemPrompt.html
/usr/share/gtk-doc/html/gcr/GcrSystemPrompter.html
/usr/share/gtk-doc/html/gcr/GcrTreeSelector.html
/usr/share/gtk-doc/html/gcr/GcrViewer.html
/usr/share/gtk-doc/html/gcr/GcrViewerWidget.html
/usr/share/gtk-doc/html/gcr/annotation-glossary.html
/usr/share/gtk-doc/html/gcr/certificate-widget.png
/usr/share/gtk-doc/html/gcr/certificates.html
/usr/share/gtk-doc/html/gcr/ch01.html
/usr/share/gtk-doc/html/gcr/collections.html
/usr/share/gtk-doc/html/gcr/combo-selector.png
/usr/share/gtk-doc/html/gcr/gcr-GcrColumn.html
/usr/share/gtk-doc/html/gcr/gcr-Key-Fingerprints.html
/usr/share/gtk-doc/html/gcr/gcr-Library-PKCS#11.html
/usr/share/gtk-doc/html/gcr/gcr-Library-Utilities.html
/usr/share/gtk-doc/html/gcr/gcr-Non-pageable-Memory.html
/usr/share/gtk-doc/html/gcr/gcr-Trust-Storage-and-Lookups.html
/usr/share/gtk-doc/html/gcr/gcr.devhelp2
/usr/share/gtk-doc/html/gcr/home.png
/usr/share/gtk-doc/html/gcr/import-button.png
/usr/share/gtk-doc/html/gcr/index.html
/usr/share/gtk-doc/html/gcr/key-widget.png
/usr/share/gtk-doc/html/gcr/left-insensitive.png
/usr/share/gtk-doc/html/gcr/left.png
/usr/share/gtk-doc/html/gcr/list-selector.png
/usr/share/gtk-doc/html/gcr/misc.html
/usr/share/gtk-doc/html/gcr/prompts.html
/usr/share/gtk-doc/html/gcr/right-insensitive.png
/usr/share/gtk-doc/html/gcr/right.png
/usr/share/gtk-doc/html/gcr/storage.html
/usr/share/gtk-doc/html/gcr/style.css
/usr/share/gtk-doc/html/gcr/tree-selector.png
/usr/share/gtk-doc/html/gcr/up-insensitive.png
/usr/share/gtk-doc/html/gcr/up.png
/usr/share/gtk-doc/html/gcr/viewer-widget.png
/usr/share/gtk-doc/html/gcr/widgets.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgck-1.so.0
/usr/lib64/libgck-1.so.0.0.0
/usr/lib64/libgcr-base-3.so.1
/usr/lib64/libgcr-base-3.so.1.0.0
/usr/lib64/libgcr-ui-3.so.1
/usr/lib64/libgcr-ui-3.so.1.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gcr-prompter
/usr/libexec/gcr-ssh-askpass

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gcr/5fb362ef1680e635fe5fb212b55eef4db9ead48f

%files locales -f gcr.lang
%defattr(-,root,root,-)

